
name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 4 * * *'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
        #下载源码
      - uses: actions/checkout@v2
        
        #使用官方脚本创建java环境
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1  
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
      - name: run Auto
        env: 
          username: ${{ secrets.username }}
          psd: ${{ secrets.psd }}
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{ secrets.clientSecret }}
        run: |
          mvn compile exec:java -Dexec.mainClass="Auto" -Dexec.args="${username} ${psd} ${clientId} ${clientSecret}"
      
