
name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 4 * * *'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
        #下载源码
      - uses: actions/checkout@v2
        
        #使用官方脚本创建java环境
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1  
        with:
          java-version: 1.8
        
        # maven缓存，不加的话每次都会去重新拉取，会影响速度   
      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml  -Dmaven.test.skip=true

      - name: run Auto
        env: 
          username: ${{ secrets.username }}
          psd: ${{ secrets.psd }}
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{ secrets.clientSecret }}
        run: |
          java -jar demo2-0.0.1-SNAPSHOT.jar "${username}" "${psd}" "${clientId}" "${clientSecret}"
        working-directory: ./target
      
